### ISSUE TITLE
cuba.Entity instead of cuba.Class

### ISSUE THREAD

**Issue by urbanmatthias** [simphony/docs#53] opened 2020-12-01 08:55 UTC
![image](https://user-images.githubusercontent.com/42069939/100718218-5c937280-33bb-11eb-935b-efde1b6819bb.png)

Maybe have a discussion on the perfect name name of the top-level class.

cuba.Class was awkward, because an instance would be a "Class" CUDS-object but should probably be an "Object" CUDS-object,

So I changed it back to what it was in the very beginning: cuba.Entity, which is also kinda awkward, because everything in the ontology is an entity, isn't it?

OWL uses owl:Thing as top-level Class.

**Comment by pablo-de-andres** [comment] 2020-12-01 08:57
Duplicate of #47
Closing that one in favour of this one

**Comment by pablo-de-andres** [comment] 2020-12-01 08:59
I'll rollback to `Entity` for now, to much the current implementation.

**Closed** 2020-12-02 12:57 UTC
Labels: discussion, ontology, simple fix
